/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhuan_ndkdemo_JNITest */

#ifndef _Included_com_zhuan_ndkdemo_JNITest
#define _Included_com_zhuan_ndkdemo_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhuan_ndkdemo_JNITest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhuan_ndkdemo_JNITest_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
